In [1]:
from PIL import Image

In [2]:
path = "imgs/1200px-NumPy_logo_2020.svg.png"
display(Image.open(path))

FileNotFoundError: [Errno 2] No such file or directory: 'imgs/1200px-NumPy_logo_2020.svg.png'

https://numpy.org/

### What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

Why Use NumPy?

Why is NumPy Faster Than Lists?

Which Language is NumPy written in?

### Installation of NumPy

In [3]:
!pip install numpy

### Import NumPy

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### What is Vectorization?

Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

Without Numpy:

In [5]:
%%time
a = [i for i in range(100000)]
b = [i for i in range(100000)]

Wall time: 13 ms


In [6]:
%%time
c = []
for i in range(len(a)):
    c.append(a[i] + 2 * b[i])

Wall time: 45.9 ms


With Numpy:

In [7]:
%%time
a = np.arange(100000)
b = np.arange(100000)

Wall time: 2.99 ms


In [8]:
%%time
c = a + 2 * b

Wall time: 1.99 ms


### NumPy as np

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### Checking NumPy Version

In [10]:
import numpy as np

print(np.__version__)

1.21.2


### Create a NumPy ndarray Object

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Dimensions in Arrays

### 0-D Arrays

In [13]:
import numpy as np

arr = np.array(42)

print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


### 1-D Arrays

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### 2-D Arrays

In [15]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


### 3-D arrays

In [16]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Check Number of Dimensions?

In [17]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Access Array Elements

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


### Access 2-D Arrays

In [21]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [22]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


### Access 3-D Arrays

In [23]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


### Negative Indexing

In [24]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


### Slicing Arrays

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[5:1])

[]


不支持反向正索引

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


### Negative Slicing

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-1:-3])

[]


不支持反向负索引

### STEP

In [60]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


### Slicing 2-D Arrays

In [32]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [33]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [34]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


### Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

### Checking the Data Type of an Array

In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [37]:
import numpy as np

arr = np.array([1.2, 2, 3, 4])

print(arr.dtype)
print(arr[1].dtype)

float64
float64


In [41]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry', 1.6666666666666666666])

print(arr.dtype)
print(arr[-1])

<U32
1.6666666666666667


In [42]:
print(arr)

['apple' 'banana' 'cherry' '1.6666666666666667']


### Converting Data Type on Existing Arrays

In [43]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [44]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [45]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


### NumPy Array Copy vs View

In [46]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [47]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


copy创建的是原ndarray的复制，改变互不影响
view创建的是ndarray的映像

In [48]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

### Check if Array Owns it's Data

In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


### Shape of an Array

In [50]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [51]:
row, col = arr.shape
print(row)
print(col)

2
4


### Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

### Reshape From 1-D to 2-D


In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 6)

print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Reshape From 1-D to 3-D

In [53]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [55]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

newarr = arr.reshape(3, 3)

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = arr.reshape(2, 4)

print(arr.base)
print(x.base)
x[0,1] = 10
print(x)
print(arr)

None
[1 2 3 4 5 6 7 8]
[[ 1 10  3  4]
 [ 5  6  7  8]]
[ 1 10  3  4  5  6  7  8]


reshape创建的是view，改变reshape后的array会同步改变原array

### Unknown Dimension

In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, -1, 2)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


就是让python自动决定一个维度，必须满足限制要求

### Flattening the arrays


In [60]:
from hashlib import new
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

newarr[1] = 9

print(newarr)

print(arr)

[1 2 3 4 5 6]
[1 9 3 4 5 6]
[[1 9 3]
 [4 5 6]]


### Iterating Arrays


In [61]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


ndarray是一种迭代器

In [62]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [63]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [64]:
row,col = arr.shape

for i in range(row):
    for j in range(col):
        print(arr[i][j])

1
2
3
4
5
6


In [65]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


### Joining NumPy Arrays

In [80]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


事实说明concatenate不能改变维度来连接

In [67]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

print(arr1)
print(arr2)
print('\n')
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)
print('\n')
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


### Joining Arrays Using Stack Functions


In [68]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking Along Rows


In [69]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stacking Along Columns


In [70]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [73]:
test_list = [np.random.randn(3, 4) for _ in range(10)]

In [76]:
new_test_arr = np.concatenate(test_list, axis=0)
print(new_test_arr.shape)

(30, 4)


In [77]:
new_test_arr1 = np.stack(test_list, axis=0)
print(new_test_arr1.shape)

(10, 3, 4)


NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

concatenate & stack区别：
- concatenate可以适用于不同维度array之间的联接，不会产生新的维度
- 例如有10个(3, 4)的ndarray，使用concatenate在axis=0的维度连接，会生成(30, 4)的array
- stack要求连接的array必须维度相同，连接会生成新的维度
- 例如有10个(3, 4)的ndarray，使用stack在axis=0的维度连接，会生成(10, 3, 4)的array

### Splitting NumPy Arrays

In [81]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [82]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [83]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


### Splitting 2-D Arrays


In [84]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

print(arr.shape)
newarr = np.array_split(arr, 3)

print(newarr)

(6, 2)
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [85]:
print(arr.shape)
print(newarr[0])
print(newarr[1])
print(newarr[2])

(6, 2)
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [86]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [87]:
print(arr.shape)
print(newarr[0])
print(newarr[1])
print(newarr[2])

(6, 3)
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


### Searching Arrays


In [88]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [92]:
y = np.where((arr == 5)|(arr == 3))
print(y)

(array([2, 4], dtype=int64),)


In [93]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [94]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


### Sorting Arrays


In [95]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [96]:
print(np.sort(arr).base)

None


没有base说明排序之后创建了一个copy

In [97]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [98]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [99]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [107]:
test_a = np.array([[1, 1], [4, 3]])
print(np.sort(test_a, axis=None).base)


None


In [105]:
test_a

array([[1, 1],
       [4, 3]])

In [108]:
np.sort(test_a, axis=0)

array([[1, 1],
       [4, 3]])

### Filtering Arrays

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

In [109]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [110]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [111]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [112]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42
print(filter_arr)

[False False  True  True]


In [113]:


newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [114]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


### Generate Random Number


In [115]:
from numpy import random

x = random.randint(100)

print(x)

59


In [116]:
x = random.randint(100)

print(x)

52


### Generate Random Float


In [117]:
from numpy import random

x = random.rand()

print(x)

0.5285907857166172


In [118]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[89 50 54 92 23]


In [119]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[31 15 93  4 39]
 [41 65 89 61 45]
 [17 99 45 35 71]]


In [120]:
from numpy import random

x = random.rand(5)

print(x)

[0.63403807 0.03053441 0.05567743 0.34041606 0.84984845]


In [121]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.89209428 0.55754488 0.21271698 0.24166978 0.8844923 ]
 [0.64818557 0.66758079 0.44412201 0.65286208 0.61390562]
 [0.14982182 0.06500989 0.15105997 0.42044884 0.3038849 ]]


### Generate Random Number From Array

In [124]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

3


In [125]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 7 9 3 9]
 [3 7 7 5 7]
 [7 5 5 7 7]]


### Random Permutations


In [126]:
# Shuffling Arrays

In [131]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

new_arr1 = random.shuffle(arr)
print(arr)
print(new_arr1)  # 根本就不会有返回值

[2 1 5 3 4]
None


In [128]:
# Generating Permutation of Arrays

In [132]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
new_arr2 = random.permutation(arr)
print(new_arr2)

[4 2 3 5 1]


### Normal Distribution


In [133]:
from numpy import random

x = random.normal(size=(2, 3))

print(x)

[[-0.82514139 -0.58974248  0.43004798]
 [-1.55855491 -0.12629783  1.2836949 ]]


### Uniform Distribution

In [134]:
from numpy import random

x = random.uniform(size=(2, 3))

print(x)

[[0.48604584 0.78759675 0.35328959]
 [0.25792657 0.3780917  0.33431425]]


#### Brief Summary

In [135]:
a = np.array([1, 2, 3])   
print(type(a))           
print(a.shape)            
print(a[0], a[1], a[2]) 
a[0] = 5                  
print(a)                  

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [136]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])    
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])  

(2, 3)
1 2 4


In [137]:
print(type(b.shape))

<class 'tuple'>


In [138]:
# Other Initializations
import numpy as np

In [139]:
a = np.zeros((2, 2)) 
print(a)

[[0. 0.]
 [0. 0.]]


In [140]:
b = np.full((2, 2), 7)
print(b)

[[7 7]
 [7 7]]


In [141]:
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [142]:
d = np.random.random((2, 2))
print(d)

[[0.10510936 0.66801576]
 [0.05084251 0.80829432]]


In [143]:
a = np.ones((2, 2))  
print(a)   

[[1. 1.]
 [1. 1.]]


In [144]:
nums = np.arange(8)
print(nums)
print(nums.min())
print(np.min(nums))

[0 1 2 3 4 5 6 7]
0
0


In [145]:
np.linspace(-1, 1, 5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [146]:
np.linspace(-1, 1, 100).shape

(100,)

### Array Operations/Math

In [147]:
x = np.array([[1, 2],
              [3, 4]], dtype='f')
y = np.array([[5, 6],
              [7, 8]], dtype='f')

In [148]:
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [149]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [150]:
print(x.dtype, y.dtype)

float32 float32


In [151]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [152]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [153]:
print(np.sqrt(x))

[[1.        1.4142135]
 [1.7320508 2.       ]]


In [154]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333334]
 [0.42857143 0.5       ]]
[[0.2        0.33333334]
 [0.42857143 0.5       ]]


In [155]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print(v.dot(w))

219


In [156]:
print(np.dot(v, w))

219


In [157]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [158]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [159]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(np.sum(x))          

21


In [160]:
print(np.sum(x, axis=0))

[5 7 9]


In [161]:
print(np.sum(x, axis=1)) 

[ 6 15]


In [162]:
print(np.max(x, axis=1))

[3 6]


In [163]:
x = np.array([[1, 2, 3],
              [3, 5, 7]])
print(x * 2) 

[[ 2  4  6]
 [ 6 10 14]]
